config/routes.rb
Rails.application.routes.draw do
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get "/articles/carting", to: "articles#carting"
  
  get 'sessions/new'
  root "sessions#new"

  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :product_name, presence: true
  validates :image, presence: true
  validates :product_price, presence: true
  validates :platform, presence: true
  validates :product_company, presence: true
  validates :product_text, length: { minimum: 10 }
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #Sessionヘルパーモジュールを読み込む
    include SessionsHelper

    private
    # ログイン済みユーザーかどうか確認
     def logged_in_user
       unless logged_in?
         redirect_to login_url
       end
     end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :logged_in_user, only:[:edit, :update, :destroy]
  #データベースのレコードを全て取り出す。
  def index
    @articles = Article.all
    @user=User.find(1)
  end
  #データベースのレコードからページIDと一致する１件を取り出す。
  def show
    @article = Article.find(params[:id])
  end
  #新しい商品を1件インスタンスする。
  def new
    @article = Article.new
  end
  #新しい商品をインスタンス化し、データベースに保存する。
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end
  #データベースから商品を取得し、インスタンス化する。
  def edit
    @article = Article.find(params[:id])
  end
  #アクションはデータベースから商品を（再）取得し、送信済みのフォームデータを更新する。
  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end
  #データベースから商品を取得してdestroyメソッドを呼び出しています。
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  #paramsハッシュに保存
  def article_params
    params.require(:article).permit(:product_name, :product_price, :product_company, :product_text, :image, :platform)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #コメント作成する。
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  #コメントを削除する。
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
  #paramsのコメントをハッシュ化
  private
  def comment_params
      params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  #ログインページから送信された情報を受け取り、ログイン処理を行う
  def create
  user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to articles_path
    else
      redirect_to articles_path
    end
  end
  #cookieに保存されたユーザーidを削除し、ログアウトを行うアクション
  def destroy
    log_out if logged_in?
    render 'new'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user
        if session[:user_id]
             @current_user ||= User.find_by(id: session[:user_id])
        end
    end
    
    def current_user?(user)
        user == current_user
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
    
end

app/views/articles/_form.html.erb
<div class="nav_zone">
  <hr class="navi_solid">
  <ul id="nav">
    <li><strong>GAMREN</strong></li>
    <li><%= link_to "商品一覧へ戻る", articles_path %></li>
    <li><%= link_to "新しい商品を登録する", new_article_path %></li>
    <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
  </ul>
  <hr class="nav_solid">
</div>
<div class="index">
  <%= form_with model: @article do |form| %>
    <div>
      <h2><label for="article_product_name">商品名</label></h2>
      <% @article.errors.full_messages_for(:product_name).each do |message| %>
        <h3 class="error">・<%= message %></h3>
      <% end %>
      <%= form.text_area :product_name %>
    </div>

    <div>
      <h2><label for="article_image">パッケージ画像</label></h2>
      <% @article.errors.full_messages_for(:image).each do |message| %>
        <h3 class="error">・画像を選択してください</h3>
      <% end %>
      <%= form.file_field :image, class: "image" %>
    </div>
      
    <div>
      <h2><label for="article_product_price">レンタル価格</label></h2>
      <% @article.errors.full_messages_for(:product_price).each do |message| %>
        <h3 class="error">・レンタル価格を選択してください</h3>
      <% end %>
      <%= form.select :product_price,  [["80円（大セール価格）", "80"], ["100円（キャンペーン価格）", "100"], ["150円（通常価格）", "150"]], include_blank: "選択して下さい"  %>
    </div>

    <div>
      <h2><label for="article_product_price">プラットフォーム</label></h2>
      <% @article.errors.full_messages_for(:product_price).each do |message| %>
        <h3 class="error">・プラットフォームを選択してください</h3>
      <% end %>
      <%= form.select :platform,  [["SWICH", "SWICH"], ["PlayStation4", "PlayStation4"], ["XBOX", "XBOX"]], include_blank: "選択して下さい"  %>
    </div>
      
    <div>
      <h2><label for="article_product_company">制作会社(架空の会社です)</label></h2>
      <% @article.errors.full_messages_for(:product_company).each do |message| %>
        <h3 class="error">・制作会社を選択してください</h3>
      <% end %>
      <%= form.select :product_company,[["LYCAN・GAME", "LYCAN・GAME"], ["PIXEL", "PIXEL"], ["フォックスエンターテインメント", "フォックスエンターテインメント"]], include_blank: "選択して下さい" %>
    </div>

    <div>
      <h2><label for="article_product_text">商品詳細</label></h2>
      <% @article.errors.full_messages_for(:product_text).each do |message| %>
        <h3 class="error">・商品詳細を10文字以上で入力してください</h3>
      <% end %>
      <%= form.text_area :product_text %>
    </div>

    <div>
      <%= form.submit value="登録"%>
    </div>
  <%end%>
 </div>

app/views/articles/_index.html.erb
<div class="nav_zone">
  <hr class="nav_solid">
  <ul id="nav">
    <li><strong>GAMREN</strong></li>
    <li><%= link_to "商品一覧へ戻る", articles_path %></li>
    <li><%= link_to "新しい商品を登録する", new_article_path %></li>
    <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
  </ul>
  <hr class="menu_solid">
</div>
<div class="index_tag">
  <h2>ゲーム一覧</h2>
</div>
<div class="index">
  <ul>
    <% @articles.each do |article| %>
      <li><h2><%= link_to article.product_name, article %></h2></li>  
    <% end %>
  </ul>
</div>

app/views/articles/_not_logged_in.html.erb
<div class="login_index">
<h1>（ログインできていません。）<h1>
<h3 class="login_error">パスワードまたはユーザIDが間違っています。</h3>
<h3 class="login_error">下記URLからもう一度ログインしてください。</h3>
<%= link_to "ログイン画面へ", login_path%>
</div>

app/views/articles/carting.html.erb
<div class="nav_zone">
  <hr class="navi_solid">
  <ul id="nav">
    <li><strong>GAMREN</strong></li>
    <li><%= link_to "商品一覧へ戻る", articles_path %></li>
    <li><%= link_to "新しい商品を登録する", new_article_path %></li>
    <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
  </ul>
  <hr class="nav_solid">
</div>
<div class="index">
  <h1>カートに入りました。(現在カート機能は追加中です。)</h1>
</div>

app/views/articles/edit.html.erb
<div class="nav_zone">
  <hr class="navi_solid">
  <ul id="nav">
    <li><strong>GAMREN</strong></li>
    <li><%= link_to "商品一覧へ戻る", articles_path %></li>
    <li><%= link_to "新しい商品を登録する", new_article_path %></li>
    <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
  </ul>
  <hr class="nav_solid">
</div>
<div class="index">
  <%= form_with model: @article do |form| %>
    <div>
      <h2><label for="article_product_name">商品名</label></h2>
      <% @article.errors.full_messages_for(:product_name).each do |message| %>
        <h3 class="error">・<%= message %>！</h3>
      <% end %>
      <%= form.text_area :product_name %>
    </div>

    <div>
      <h2><label for="article_image">パッケージ画像(変更したい場合はファイルを選択してください)</label></h2>
      <% @article.errors.full_messages_for(:image).each do |message| %>
        <h3 class="error">・画像を選択してください！</h3>
      <% end %>
      <%= form.file_field :image, class: "image" %>
    </div>
      
    <div>
      <h2><label for="article_product_price">レンタル価格</label></h2>
      <% @article.errors.full_messages_for(:product_price).each do |message| %>
        <h3 class="error">・レンタル価格を選択してください！</h3>
      <% end %>
      <%= form.select :product_price,  [["80円（大セール価格）", "80"], ["100円（キャンペーン価格）", "100"], ["150円（通常価格）", "150"]], include_blank: "選択して下さい"  %>
    </div>

    <div>
      <h2><label for="article_product_price">プラットフォーム</label></h2>
      <% @article.errors.full_messages_for(:platform).each do |message| %>
        <h3 class="error">・プラットフォームを選択してください</h3>
      <% end %>
      <%= form.select :platform,  [["SWICH", "SWICH"], ["PlayStation4", "PlayStation4"], ["XBOX", "XBOX"]], include_blank: "選択して下さい"  %>
    </div>
      
    <div>
      <h2><label for="article_product_company">制作会社(架空の会社です)</label></h2>
      <% @article.errors.full_messages_for(:product_company).each do |message| %>
        <h3 class="error">・制作会社を選択してください！</h3>
      <% end %>
      <%= form.select :product_company,[["LYCAN・GAME", "LYCAN・GAME"], ["PIXEL", "PIXEL"], ["フォックスエンターテインメント", "フォックスエンターテインメント"]], include_blank: "選択して下さい" %>
    </div>

    <div>
      <h2><label for="article_product_text">商品詳細</label></h2>
      <% @article.errors.full_messages_for(:product_text).each do |message| %>
        <h3 class="error">・商品詳細を10文字以上で入力してください！</h3>
      <% end %>
      <%= form.text_area :product_text %>
    </div>

    <div>
      <%= form.submit value="登録"%>
    </div>
  <%end%>
</div>

app/views/articles/index.html.erb
<% if logged_in? %>
  <%= render 'articles/index' %>
<% else %>
  <%= render 'articles/not_logged_in' %>
<% end %>

app/views/articles/introduction.html.erb
<div class="nav_zone">
  <hr class="navi_solid">
  <ul id="nav">
    <li><strong>GAMREN</strong></li>
    <li><%= link_to "商品一覧へ戻る", articles_path %></li>
    <li><%= link_to "新しい商品を登録する", new_article_path %></li>
    <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
  </ul>
  <hr class="nav_solid">
</div>
<div class="index_tag">
  <h2>ゲムレンについて</h2>
</div>
<div class="index">

  </ul>
</div>

app/views/articles/new.html.erb
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="nav_zone">
  <hr class="navi_solid">
  <ul id="nav">
    <li><strong>GAMREN</strong></li>
    <li><%= link_to "商品一覧へ戻る", articles_path %></li>
    <li><%= link_to "新しい商品を登録する", new_article_path %></li>
    <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
  </ul>
  <hr class="nav_solid">
</div>
<div class="index">
    <h1>「<%= @article.product_name %>」</h1>
    <hr>
    <%= image_tag @article.image.url, class: "product_image" %>
    
    <h2>レンタル価格</h2>
    <p><%= @article.product_price %>円</p>

    <h2>プラットフォーム</h2>
    <p><%= @article.platform %></p>

    <h2>制作会社</h2>
    <p><%= @article.product_company %></p>

    <h2>詳細</h2>
    <p><%= @article.product_text %></p>

    <ul>
        <li><%= link_to "カートに入れる", articles_carting_path(@article)%></li>
        <li><%= link_to "商品情報を更新する", edit_article_path(@article) %></li>
        <li><%= link_to "商品情報を削除する", article_path(@article),
                        method: :delete,
                        data: { confirm: "本当に商品登録を削除しますか?" } %></li>
    </ul>

    <h2>レビュ一覧</h2>
    <hr>
    <%= render @article.comments %>
    

    <h2>レビューを追加する</h2>
    <%= render "comments/form" %>
</div>

app/views/comments/_comment.html.erb
<p>
  <%= comment.commenter %>さん
</p>

<p>

  「<%= comment.body %>」

</p>

<p><%= link_to 'このレビューを削除', [comment.article, comment],
              method: :delete,
              data: { confirm: "レビューを削除する" } %>
</p>
<hr>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <label for="comment_commenter">ユーザ名</label><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <label for="comment_body">レビュー内容</label><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit value="レビューを投稿する"%>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GamRen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>